service:
  name: profile-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  main:
    handler: dist/src/serverless.handler
    events:
      - http:
          method: any
          path: /{any+}
